import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
export type UiState='loading'|'empty'|'error'|'offline';
@Component({selector:'app-state-view',standalone:true,imports:[CommonModule],template:`
@if(state==='loading'){<div class="state loading" [class.compact]="compact"><div class="skeleton-icon"></div><div class="lines"><i></i><i></i><i></i></div><span>{{loadingLabel}}</span></div>}
@if(state==='empty'){<section class="state-card empty"><div class="illustration empty-icon"><span>◇</span></div><div><span class="eyebrow">NOTHING HERE YET</span><h3>{{title||'No data found'}}</h3><p>{{message||'There is nothing to show right now. Try adjusting your filters or create something new.'}}</p>@if(actionLabel){<button type="button" (click)="action.emit()">{{actionLabel}} <b>→</b></button>}</div></section>}
@if(state==='error'){<section class="state-card error"><div class="illustration"><span>!</span></div><div><span class="eyebrow">SOMETHING WENT WRONG</span><h3>{{title||'Unable to load this data'}}</h3><p>{{message||'We could not complete your request. Check your connection and try again.'}}</p><div class="actions"><button type="button" (click)="retry.emit()">Try again <b>↻</b></button>@if(actionLabel){<button class="secondary" type="button" (click)="action.emit()">{{actionLabel}}</button>}</div></div></section>}
@if(state==='offline'){<section class="state-card offline"><div class="illustration"><span>⌁</span></div><div><span class="eyebrow">CONNECTION LOST</span><h3>{{title||'You appear to be offline'}}</h3><p>{{message||'Reconnect to continue syncing live CricPulse data.'}}</p><button type="button" (click)="retry.emit()">Check connection <b>↻</b></button></div></section>}
`,styles:[`:host{display:block}.state{position:relative}.loading{display:grid;grid-template-columns:48px 1fr auto;align-items:center;gap:13px;padding:16px;border:1px solid var(--cp-border);border-radius:15px;background:var(--cp-surface)}.loading.compact{padding:10px}.skeleton-icon,.lines i{position:relative;overflow:hidden;background:var(--cp-surface-raised);border-radius:8px}.skeleton-icon{width:48px;height:48px}.lines{display:grid;gap:7px}.lines i{height:8px;width:80%}.lines i:nth-child(2){width:56%}.lines i:nth-child(3){width:35%}.skeleton-icon:after,.lines i:after{content:'';position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,color-mix(in srgb,var(--cp-text) 7%,transparent),transparent);animation:shimmer 1.25s infinite}.loading>span{color:var(--cp-text-muted);font-size:9px;font-weight:800}.state-card{display:grid;grid-template-columns:74px 1fr;gap:20px;align-items:start;padding:26px;border:1px solid var(--cp-border);border-radius:20px;background:linear-gradient(135deg,var(--cp-surface),var(--cp-surface-raised));box-shadow:var(--cp-shadow-sm)}.illustration{display:grid;place-items:center;width:64px;height:64px;border-radius:20px;background:var(--cp-accent-soft);color:var(--cp-accent);font-size:26px;font-weight:950}.error .illustration{background:color-mix(in srgb,#ff6b6b 12%,transparent);color:#e87b7b}.offline .illustration{background:color-mix(in srgb,#f2a65a 14%,transparent);color:#d58b43}.eyebrow{display:block;color:var(--cp-accent);font-size:8px;font-weight:950;letter-spacing:.15em}.error .eyebrow{color:#df7a7a}.offline .eyebrow{color:#d58b43}.state-card h3{margin:7px 0;font-size:17px;letter-spacing:-.025em}.state-card p{max-width:580px;margin:0;color:var(--cp-text-muted);font-size:11px;line-height:1.65}.state-card button{margin-top:16px;border:0;border-radius:10px;padding:10px 13px;background:var(--cp-accent);color:var(--cp-accent-contrast);font:850 10px inherit;cursor:pointer}.state-card button b{margin-left:7px;font-size:13px}.actions{display:flex;gap:8px}.state-card button.secondary{border:1px solid var(--cp-border);background:transparent;color:var(--cp-text)}@keyframes shimmer{to{transform:translateX(100%)}}@media(max-width:520px){.loading{grid-template-columns:42px 1fr}.loading>span{display:none}.skeleton-icon{width:42px;height:42px}.state-card{grid-template-columns:1fr;padding:21px;gap:14px}.illustration{width:54px;height:54px}.actions{flex-wrap:wrap}}`]
}) export class StateViewComponent{
 @Input() state:UiState='empty';@Input() title='';@Input() message='';@Input() actionLabel='';@Input() loadingLabel='Loading data...';@Input() compact=false;
 @Output() retry=new EventEmitter<void>();
 @Output() action=new EventEmitter<void>();
}