import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

interface Team { id:string; name:string; city?:string; ownerId:string; }
interface Row { fullName:string; email:string; phone:string; password:string; }
interface Result { created:any[]; skipped:any[]; createdCount:number; skippedCount:number; }

@Component({
 selector:'app-bulk-team-players-v2', standalone:true, imports:[CommonModule,FormsModule,RouterLink],
 template:`<section class="page">@if(team){
 <header class="hero"><div><a [routerLink]="['/dashboard/teams',team.id]">← Back to Team</a><div class="eyebrow">SQUAD BUILDER</div><h1>Create Player Accounts</h1><p>{{team.name}} · Create and add many PLAYER accounts in one step.</p></div><span class="badge">MAX 50 / BATCH</span></header>
 <section class="card"><div class="head"><div><div class="eyebrow">QUICK CREATE</div><h2>Generate Test Squad</h2><p>Generate 11, 15, 22 or any number of players. Edit names/details before creating.</p></div><div class="generate"><label>Players <input type="number" min="1" max="50" [(ngModel)]="count"></label><button class="secondary" (click)="generate()">Generate</button></div></div><div class="hint">Default temporary password: <b>Test&#64;12345</b>. Each generated account gets a unique email and mobile number.</div></section>
 <section class="card"><div class="head"><div><div class="eyebrow">PLAYER ACCOUNTS</div><h2>{{rows.length}} ready</h2></div><div class="buttons"><button class="ghost" (click)="rows=[]">Clear</button><button class="primary" [disabled]="saving||!rows.length" (click)="create()">{{saving?'Creating…':'Create & Add All'}}</button></div></div>
 <div class="table"><table><thead><tr><th>#</th><th>Name</th><th>Email</th><th>Mobile</th><th>Password</th><th></th></tr></thead><tbody>@for(r of rows;track $index;let i=$index){<tr><td>{{i+1}}</td><td><input [(ngModel)]="r.fullName"></td><td><input [(ngModel)]="r.email"></td><td><input [(ngModel)]="r.phone"></td><td><input [(ngModel)]="r.password"></td><td><button class="x" (click)="remove(i)">×</button></td></tr>}@empty{<tr><td colspan="6" class="empty">Click Generate to create your squad list.</td></tr>}</tbody></table></div></section>
 @if(result){<section class="card"><div class="head"><div><div class="eyebrow">CREATED</div><h2>{{result.createdCount}} added · {{result.skippedCount}} skipped</h2></div></div><div class="results">@for(p of result.created;track p.playerId){<div><b>{{p.fullName}}</b><span>{{p.email}} · {{p.phone}}</span><code>{{p.temporaryPassword||'Existing account'}}</code></div>}</div><p class="warning">Save the temporary passwords if these players need to login. Passwords are never stored in plain text.</p>@if(result.skipped.length){<div class="skipped">@for(p of result.skipped;track $index){<div><b>{{p.fullName||p.email}}</b> — {{p.reason}}</div>}</div>}</section>}
 @if(toast){<div class="toast" [class.error]="error">{{toast}}</div>}
 }@else{<div class="loading">Loading team…</div>}</section>`,
 styles:[`:host{display:block}.page{max-width:1250px;padding:38px 4vw 100px;color:#edf8f2}.hero,.head{display:flex;justify-content:space-between;align-items:end;gap:20px}.hero{margin-bottom:22px}.hero a{display:inline-block;color:#91aa9d;text-decoration:none;font-size:12px;margin-bottom:15px}.eyebrow{color:#b8f45c;font-size:10px;font-weight:850;letter-spacing:2px}.hero h1{font-size:clamp(36px,5vw,58px);letter-spacing:-3px;margin:8px 0}.hero p,.card p{color:#91aa9d;font-size:11px;margin:0}.badge{padding:9px 12px;border:1px solid #b8f45c33;color:#b8f45c;border-radius:99px;font-size:9px;font-weight:900}.card{background:#0c2119df;border:1px solid #ffffff15;border-radius:20px;padding:20px;margin-bottom:18px}.card h2{margin:7px 0;font-size:24px}.generate,.buttons{display:flex;gap:9px;align-items:end}.generate label{display:grid;gap:5px;color:#789386;font-size:9px;text-transform:uppercase}.generate input,.table input{background:#081a14;color:#edf8f2;border:1px solid #ffffff18;border-radius:8px;padding:10px}.generate input{width:80px}.primary,.secondary,.ghost{border:0;border-radius:9px;padding:11px 15px;font-weight:850;cursor:pointer}.primary{background:#b8f45c;color:#10251e}.secondary{background:#173d2d;color:#b8f45c}.ghost{background:#0c2119;color:#dbe9e1;border:1px solid #ffffff18}.primary:disabled{opacity:.4}.hint{margin-top:18px;padding:11px;background:#b8f45c08;border:1px solid #b8f45c20;border-radius:10px;color:#91aa9d;font-size:10px}.hint b{color:#b8f45c}.table{overflow:auto;border:1px solid #ffffff0d;border-radius:12px;margin-top:18px}table{width:100%;border-collapse:collapse;min-width:900px}th,td{padding:8px;border-bottom:1px solid #ffffff0a;text-align:left;font-size:11px}th{font-size:9px;color:#789386;text-transform:uppercase;background:#081a14}.table input{width:100%;box-sizing:border-box}.x{border:0;background:transparent;color:#ff9b9b;font-size:20px}.empty{text-align:center;padding:40px;color:#789386}.results{display:grid;gap:7px;margin-top:18px}.results>div{display:grid;grid-template-columns:180px 1fr 130px;gap:10px;align-items:center;padding:10px;border-radius:9px;background:#081a14;border:1px solid #ffffff0c}.results span{color:#789386;font-size:10px}.results code{color:#b8f45c}.warning{color:#ffcf7a!important;margin-top:14px!important}.skipped{margin-top:12px;display:grid;gap:5px;color:#ffb5b5;font-size:10px}.toast{position:fixed;right:24px;bottom:24px;background:#173d2d;border:1px solid #b8f45c55;border-radius:12px;padding:13px 16px;z-index:1000}.toast.error{border-color:#ff6b6b66}.loading{text-align:center;padding:100px;color:#789386}@media(max-width:700px){.hero,.head{align-items:stretch;flex-direction:column}.generate{align-items:stretch}.buttons{width:100%}.buttons button{flex:1}.results>div{grid-template-columns:1fr}}`]
})
export class BulkTeamPlayersV2Component {
 private http=inject(HttpClient); private route=inject(ActivatedRoute); private api='http://localhost:8080/api';
 team:Team|null=null; rows:Row[]=[]; count=15; saving=false; result:Result|null=null; toast=''; error=false;
 constructor(){const id=this.route.snapshot.paramMap.get('id');if(id)this.http.get<Team>(`${this.api}/teams/${id}`).subscribe({next:t=>this.team=t,error:e=>this.show(e?.error?.message||'Unable to load team',true)})}
 generate(){const n=Math.max(1,Math.min(50,Number(this.count)||15)),stamp=Date.now(),slug=(this.team?.name||'team').toLowerCase().replace(/[^a-z0-9]+/g,'-');this.count=n;this.rows=Array.from({length:n},(_,i)=>({fullName:`Player ${String(i+1).padStart(2,'0')}`,email:`player${String(i+1).padStart(2,'0')}.${stamp}@${slug}.cricpulse.test`,phone:String(9000000000+((stamp+i*7919)%999999999)),password:'Test@12345'}));this.result=null}
 remove(i:number){this.rows.splice(i,1);this.rows=[...this.rows]}
 create(){if(!this.team||!this.rows.length)return;this.saving=true;this.http.post<Result>(`${this.api}/teams/${this.team.id}/players/bulk`,{players:this.rows}).subscribe({next:r=>{this.result=r;this.rows=[];this.saving=false;this.show(`${r.createdCount} player accounts created and added`,false)},error:e=>{this.saving=false;this.show(e?.error?.message||'Unable to create players',true)}})}
 show(m:string,e:boolean){this.toast=m;this.error=e;window.setTimeout(()=>this.toast='',4000)}
}
