import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { DateTimeFieldComponent } from './ui/date-time-field.component';
import { SelectFieldComponent, SelectOption } from './ui/select-field.component';

interface Team { id: string; name: string; }

@Component({
  selector: 'app-create-match', standalone: true,
  imports: [FormsModule, RouterLink, SelectFieldComponent, DateTimeFieldComponent],
  template: `<section class="create-page">
    <div class="ambient a1"></div><div class="ambient a2"></div>
    <a class="back" routerLink="/matches"><span>←</span> MATCH WORKSPACE</a>
    <header class="hero"><div><div class="eyebrow"><i></i> NEW MATCH PROTOCOL</div><h1>Build the next<br><em>matchday.</em></h1><p>Set the essentials now. Lineups, toss and live scoring follow in a guided workflow.</p></div><div class="hero-orbit"><span>01</span><small>SETUP<br>OF 03</small></div></header>
    <form (ngSubmit)="submit()" #matchForm="ngForm">
      <div class="form-shell">
        <div class="shell-top"><div><span class="step-tag">STEP 01</span><h2>Match configuration</h2><p>Define the fixture and its playing conditions.</p></div><div class="progress"><span class="active"></span><span></span><span></span></div></div>
        <div class="form-grid">
          <label class="field wide"><span>Match identity <b>Required</b></span><div class="input-wrap"><i>⌕</i><input name="name" [(ngModel)]="form.name" placeholder="e.g. Sunday League Final" required /></div><small>Give this fixture a clear, recognizable name.</small></label>
          <div class="field-group"><app-select-field label="Match format" name="format" [options]="formatOptions" [(value)]="form.format" /><small>Controls the match structure.</small></div>
          <label class="field"><span>Overs per innings</span><div class="input-wrap"><input name="overs" type="number" min="1" [(ngModel)]="form.overs" /><em>OVERS</em></div><small>Can be adjusted for custom formats.</small></label>
          <div class="team-section wide"><div class="section-label"><span><i></i> THE CONTEST</span><p>Select the two sides entering this fixture.</p></div><div class="team-grid"><div class="team-slot"><span class="slot-no">A</span><app-select-field label="Home / your team" name="teamAId" placeholder="Select team" [options]="teamOptions" [(value)]="form.teamAId" /></div><div class="versus">VS</div><div class="team-slot"><span class="slot-no away">B</span><app-select-field label="Opponent team" name="teamBId" placeholder="Select opponent" [options]="teamOptions" [(value)]="form.teamBId" /></div></div></div>
          <app-date-time-field label="Scheduled date & time" name="scheduledAt" [(value)]="form.scheduledAt" />
          <label class="field"><span>Venue <b>Optional</b></span><div class="input-wrap"><i>⌖</i><input name="venue" [(ngModel)]="form.venue" placeholder="Ground or venue name" /></div></label>
        </div>
        <div class="advanced"><div class="advanced-copy"><div class="advanced-icon">✦</div><div><span>EXTENDED RULESET</span><h3>Advanced settings</h3><p>Powerplay, super over and rain rules can be configured after the fixture is created.</p></div></div><div class="chips"><span>POWERPLAY</span><span>SUPER OVER</span><span>DLS READY</span></div></div>
      </div>
      @if(error){<div class="error"><i>!</i>{{error}}</div>}
      <footer class="actions"><a routerLink="/matches">Discard changes</a><div class="action-right"><span>All changes are validated</span><button [disabled]="loading">{{loading?'Creating match...':'Create match'}} <b>→</b></button></div></footer>
    </form>
  </section>`  styles: [`:host{display:block;--ink:var(--cp-text);--muted:var(--cp-text-muted);--line:var(--cp-border);--surface:var(--cp-surface);--raised:var(--cp-surface-raised);--accent:var(--cp-accent);--accent-soft:var(--cp-accent-soft)}
.create-page{position:relative;isolation:isolate;max-width:1240px;margin:0 auto;padding:42px 4vw 100px;overflow:hidden}.ambient{position:absolute;z-index:-1;pointer-events:none;border-radius:50%;filter:blur(80px);opacity:.1}.a1{width:360px;height:360px;background:var(--accent);right:-150px;top:90px}.a2{width:260px;height:260px;background:#5da9ff;left:-150px;bottom:100px}
.back{display:inline-flex;align-items:center;gap:9px;color:var(--muted);text-decoration:none;font-size:9px;font-weight:850;letter-spacing:1.7px;margin-bottom:40px;transition:.2s}.back span{font-size:16px;line-height:1}.back:hover{color:var(--accent);transform:translateX(-2px)}
.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:30px;margin-bottom:30px}.eyebrow{display:flex;align-items:center;gap:8px;color:var(--accent);font-size:9px;font-weight:900;letter-spacing:2px}.eyebrow i{width:6px;height:6px;border-radius:50%;background:var(--accent);box-shadow:0 0 14px var(--accent)}.hero h1{margin:13px 0 10px;font-size:clamp(32px,4vw,50px);line-height:1.02;letter-spacing:-2.4px;font-weight:800}.hero h1 em{font-style:normal;color:var(--accent)}.hero p{max-width:520px;margin:0;color:var(--muted);font-size:12px;line-height:1.65}.hero-orbit{width:78px;height:78px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;align-content:center;background:var(--surface);position:relative;box-shadow:0 0 0 8px color-mix(in srgb,var(--accent) 3%,transparent)}.hero-orbit:after{content:'';position:absolute;inset:-4px;border:1px dashed color-mix(in srgb,var(--accent) 28%,transparent);border-radius:50%;animation:spin 18s linear infinite}.hero-orbit span{font-size:22px;font-weight:850;letter-spacing:-1px}.hero-orbit small{text-align:center;color:var(--muted);font-size:6px;font-weight:850;letter-spacing:1px;line-height:1.35}
.form-shell{padding:28px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(145deg,var(--surface),var(--raised));box-shadow:0 26px 70px color-mix(in srgb,#000 13%,transparent)}.shell-top{display:flex;justify-content:space-between;gap:20px;padding-bottom:22px;border-bottom:1px solid var(--line)}.step-tag{color:var(--accent);font-size:8px;font-weight:900;letter-spacing:1.7px}.shell-top h2{margin:7px 0 5px;font-size:20px;letter-spacing:-.7px}.shell-top p{margin:0;color:var(--muted);font-size:10px}.progress{display:flex;align-items:center;gap:6px}.progress span{width:22px;height:3px;border-radius:3px;background:var(--line)}.progress span.active{width:38px;background:var(--accent);box-shadow:0 0 14px color-mix(in srgb,var(--accent) 50%,transparent)}
.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;padding:26px 0}.wide{grid-column:1/-1}.field,.field-group{display:grid;gap:8px}.field>span{display:flex;align-items:center;justify-content:space-between;color:var(--ink);font-size:11px;font-weight:760}.field b{font-size:7px;text-transform:uppercase;letter-spacing:1px;color:var(--accent)}.field>small,.field-group>small{margin-top:-3px;color:var(--muted);font-size:9px}.input-wrap{height:48px;box-sizing:border-box;display:flex;align-items:center;gap:9px;padding:0 13px;border:1px solid var(--line);border-radius:12px;background:color-mix(in srgb,var(--cp-text) 2%,transparent);transition:.2s}.input-wrap:focus-within{border-color:color-mix(in srgb,var(--accent) 55%,var(--line));box-shadow:0 0 0 3px var(--accent-soft);background:var(--surface)}.input-wrap i{color:var(--muted);font-style:normal}.input-wrap input{min-width:0;flex:1;height:100%;border:0;outline:0;background:transparent;color:var(--ink);font:inherit;font-size:12px}.input-wrap input::placeholder{color:var(--muted)}.input-wrap em{font-size:8px;font-style:normal;font-weight:850;letter-spacing:1px;color:var(--muted)}
.team-section{padding:20px;border:1px solid var(--line);border-radius:16px;background:color-mix(in srgb,var(--accent) 2.5%,transparent)}.section-label{display:flex;justify-content:space-between;align-items:center;margin-bottom:17px}.section-label span{display:flex;align-items:center;gap:7px;color:var(--accent);font-size:8px;font-weight:900;letter-spacing:1.6px}.section-label i{width:5px;height:5px;border-radius:50%;background:var(--accent)}.section-label p{margin:0;color:var(--muted);font-size:9px}.team-grid{display:grid;grid-template-columns:1fr 42px 1fr;align-items:center;gap:12px}.team-slot{position:relative}.slot-no{position:absolute;z-index:2;right:13px;top:-4px;width:19px;height:19px;border-radius:50%;display:grid;place-items:center;background:var(--accent);color:#152018;font-size:9px;font-weight:900}.slot-no.away{background:color-mix(in srgb,#63aaff 75%,var(--surface));color:#fff}.versus{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;border:1px solid var(--line);background:var(--raised);color:var(--muted);font-size:8px;font-weight:900}
.advanced{display:flex;justify-content:space-between;align-items:center;gap:25px;padding:18px 19px;border:1px solid var(--line);border-radius:15px;background:color-mix(in srgb,var(--cp-text) 2%,transparent)}.advanced-copy{display:flex;gap:12px;align-items:center}.advanced-icon{width:35px;height:35px;border-radius:11px;display:grid;place-items:center;background:var(--accent-soft);color:var(--accent);font-size:15px}.advanced-copy span{font-size:8px;font-weight:900;color:var(--accent);letter-spacing:1.4px}.advanced-copy h3{margin:3px 0;font-size:13px}.advanced-copy p{margin:0;color:var(--muted);font-size:9px}.chips{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.chips span{padding:7px 9px;border-radius:7px;border:1px solid var(--line);color:var(--muted);font-size:8px;font-weight:800;letter-spacing:.5px;background:var(--surface)}
.error{display:flex;align-items:center;gap:8px;margin-top:14px;padding:12px 14px;border:1px solid color-mix(in srgb,#ff5f6d 28%,var(--line));border-radius:11px;background:color-mix(in srgb,#ff5f6d 6%,transparent);color:#e86d76;font-size:10px}.error i{width:17px;height:17px;border-radius:50%;display:grid;place-items:center;background:#e86d76;color:#fff;font-style:normal;font-weight:900}
.actions{display:flex;justify-content:space-between;align-items:center;padding:22px 3px}.actions>a{color:var(--muted);font-size:10px;text-decoration:none}.actions>a:hover{color:var(--ink)}.action-right{display:flex;align-items:center;gap:18px}.action-right>span{color:var(--muted);font-size:9px}.actions button{height:46px;padding:0 18px;border:0;border-radius:12px;background:var(--accent);color:#142018;font-size:11px;font-weight:900;cursor:pointer;box-shadow:0 14px 30px color-mix(in srgb,var(--accent) 16%,transparent);transition:.2s}.actions button:hover:not(:disabled){transform:translateY(-2px);box-shadow:0 18px 35px color-mix(in srgb,var(--accent) 24%,transparent)}.actions button:disabled{opacity:.6;cursor:not-allowed}.actions button b{margin-left:16px;font-size:15px}
@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:760px){.create-page{padding:30px 18px 80px}.hero{align-items:flex-start}.hero-orbit{display:none}.form-shell{padding:20px}.shell-top{align-items:flex-start}.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}.team-section{grid-column:auto}.team-grid{grid-template-columns:1fr;gap:10px}.versus{justify-self:center}.section-label{align-items:flex-start;gap:10px;flex-direction:column}.advanced{align-items:flex-start;flex-direction:column}.chips{justify-content:flex-start}.actions{gap:20px;align-items:flex-start;flex-direction:column}.action-right{width:100%;justify-content:space-between}.action-right>span{display:none}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;transition-duration:.01ms!important}}`]

})
export class CreateMatchComponent {
  private readonly http = inject(HttpClient); private readonly router = inject(Router);
  teams: Team[] = []; loading = false; error = '';
  form = { name: '', format: 'T20', overs: 20, teamAId: '', teamBId: '', scheduledAt: '', venue: '' };
  formatOptions: SelectOption[] = [{value:'T20',label:'T20'}, {value:'T10',label:'T10'}, {value:'ODI',label:'ODI'}, {value:'TEST',label:'Test'}, {value:'CUSTOM',label:'Custom format'}];
  get teamOptions(): SelectOption[] { return this.teams.map(team => ({ value: team.id, label: team.name })); }
  constructor() { this.loadTeams(); }
  loadTeams(): void { const saved = localStorage.getItem('cricketpulse_team'); const active = saved ? JSON.parse(saved) as Team : null; this.http.get<Team[]>('http://localhost:8080/api/teams').subscribe({ next: teams => { this.teams = teams; this.form.teamAId = active?.id || teams[0]?.id || ''; }, error: () => { if (active) { this.teams = [active]; this.form.teamAId = active.id; } } }); }
  submit(): void {
    this.error = '';
    if (!this.form.name.trim() || !this.form.teamAId || !this.form.teamBId) { this.error = 'Complete the match name and select both teams.'; return; }
    if (this.form.teamAId === this.form.teamBId) { this.error = 'Your team and opponent must be different teams.'; return; }
    this.loading = true;
    this.http.post('http://localhost:8080/api/matches', { name: this.form.name.trim(), format: this.form.format, teamAId: this.form.teamAId, teamBId: this.form.teamBId, scheduledAt: this.form.scheduledAt ? new Date(this.form.scheduledAt).toISOString() : null }).subscribe({ next: () => void this.router.navigateByUrl('/matches'), error: () => { this.loading = false; this.error = 'Match could not be created. Check the selected teams and try again.'; } });
  }
}
