import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { DateTimeFieldComponent } from './ui/date-time-field.component';
import { SelectFieldComponent, SelectOption } from './ui/select-field.component';

interface Team { id: string; name: string; }

@Component({
  selector: 'app-create-match', standalone: true,
  imports: [FormsModule, RouterLink, SelectFieldComponent, DateTimeFieldComponent],
  template: `<section class="create-page"><a class="back" routerLink="/matches">← Back to matches</a><div class="heading"><div class="eyebrow">MATCHDAY SETUP</div><h1>Create a<br><em>new match.</em></h1><p>Configure the match now. Playing XI, toss, and scoring come next.</p></div><form (ngSubmit)="submit()"><div class="form-header"><div><b>Match details</b><small>Start with the essentials</small></div><span>01 / 03</span></div><div class="form-grid"><label class="field wide"><span>Match name</span><input name="name" [(ngModel)]="form.name" placeholder="e.g. Sunday League Final" required /></label><app-select-field label="Format" name="format" [options]="formatOptions" [(value)]="form.format" /><label class="field"><span>Overs per innings</span><input name="overs" type="number" min="1" [(ngModel)]="form.overs" /></label><app-select-field label="Your team" name="teamAId" placeholder="Select team" [options]="teamOptions" [(value)]="form.teamAId" /><app-select-field label="Opponent team" name="teamBId" placeholder="Select opponent" [options]="teamOptions" [(value)]="form.teamBId" /><app-date-time-field label="Date and time" name="scheduledAt" [(value)]="form.scheduledAt" /><label class="field"><span>Venue</span><input name="venue" [(ngModel)]="form.venue" placeholder="Ground or venue name" /></label></div><div class="advanced"><div><b>Advanced match settings</b><small>Configure these later from match settings</small></div><div class="chips"><span>⚡ Powerplay</span><span>↻ Super over</span><span>☁ DLS rules</span></div></div>@if(error){<p class="error">{{error}}</p>}<div class="actions"><a routerLink="/matches">Cancel</a><button [disabled]="loading">{{loading?'Creating match...':'Create match'}} <b>→</b></button></div></form></section>`,
  styles: [`:host{display:block}.create-page{max-width:1120px;padding:45px 4vw 100px}.back{display:inline-block;color:#91aa9d;text-decoration:none;font-size:12px;margin-bottom:55px}.back:hover{color:#b8f45c}.heading{margin-bottom:34px}.eyebrow{color:#b8f45c;font-size:10px;font-weight:850;letter-spacing:2px}.heading h1{margin:17px 0 10px;font-size:clamp(48px,7vw,76px);line-height:.93;letter-spacing:-5px}.heading em{color:#91aa9d;font-style:normal}.heading p{color:#91aa9d}.create-page form{max-width:1050px;padding:28px;border:1px solid #ffffff18;border-radius:22px;background:#0c2119d9;box-shadow:0 20px 55px #0004}.form-header{display:flex;justify-content:space-between;padding-bottom:21px;border-bottom:1px solid #ffffff12}.form-header div{display:grid;gap:5px}.form-header small{color:#789386;font-size:11px}.form-header>span{color:#b8f45c;font-size:10px;font-weight:850}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;padding:25px 0}.wide{grid-column:1/-1}.field{display:grid;gap:8px;color:#b9ccc2;font-size:12px;font-weight:750}.field input{box-sizing:border-box;width:100%;height:50px;padding:0 15px;border:1px solid #ffffff1c;border-radius:11px;background:linear-gradient(135deg,#ffffff0c,#ffffff05);color:#fff;outline:none;font:inherit}.field input:focus{border-color:#b8f45c;box-shadow:0 0 0 3px #b8f45c18}.advanced{display:flex;justify-content:space-between;gap:20px;padding:18px;border:1px solid #ffffff12;border-radius:12px;background:#ffffff06}.advanced div:first-child{display:grid;gap:5px}.advanced small{color:#789386;font-size:10px}.chips{display:flex;flex-wrap:wrap;gap:7px;justify-content:flex-end}.chips span{padding:7px 9px;border-radius:7px;background:#ffffff08;color:#91aa9d;font-size:10px}.actions{display:flex;justify-content:flex-end;align-items:center;gap:20px;margin-top:25px}.actions a{color:#91aa9d;text-decoration:none;font-size:12px}.actions button{padding:14px 18px;border:0;border-radius:10px;background:#b8f45c;color:#10251e;font-weight:850;cursor:pointer}.actions button b{margin-left:18px}.actions button:disabled{opacity:.6}.error{color:#ffaaa4;font-size:12px}@media(max-width:650px){.create-page{padding:35px 20px 90px}.back{margin-bottom:38px}.heading h1{letter-spacing:-3px}.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}.advanced{flex-direction:column}.chips{justify-content:flex-start}.actions{justify-content:space-between}}`]
})
export class CreateMatchComponent {
  private readonly http = inject(HttpClient); private readonly router = inject(Router);
  teams: Team[] = []; loading = false; error = '';
  form = { name: '', format: 'T20', overs: 20, teamAId: '', teamBId: '', scheduledAt: '', venue: '' };
  formatOptions: SelectOption[] = [{value:'T20',label:'T20'}, {value:'T10',label:'T10'}, {value:'ODI',label:'ODI'}, {value:'TEST',label:'Test'}, {value:'CUSTOM',label:'Custom format'}];
  get teamOptions(): SelectOption[] { return this.teams.map(team => ({ value: team.id, label: team.name })); }
  constructor() { this.loadTeams(); }
  loadTeams(): void { const saved = localStorage.getItem('cricketpulse_team'); const active = saved ? JSON.parse(saved) as Team : null; this.http.get<Team[]>('http://localhost:8080/api/teams').subscribe({ next: teams => { this.teams = teams; this.form.teamAId = active?.id || teams[0]?.id || ''; }, error: () => { if (active) { this.teams = [active]; this.form.teamAId = active.id; } } }); }
  submit(): void {
    this.error = '';
    if (!this.form.name.trim() || !this.form.teamAId || !this.form.teamBId) { this.error = 'Complete the match name and select both teams.'; return; }
    if (this.form.teamAId === this.form.teamBId) { this.error = 'Your team and opponent must be different teams.'; return; }
    this.loading = true;
    this.http.post('http://localhost:8080/api/matches', { name: this.form.name.trim(), format: this.form.format, teamAId: this.form.teamAId, teamBId: this.form.teamBId, scheduledAt: this.form.scheduledAt ? new Date(this.form.scheduledAt).toISOString() : null }).subscribe({ next: () => void this.router.navigateByUrl('/matches'), error: () => { this.loading = false; this.error = 'Match could not be created. Check the selected teams and try again.'; } });
  }
}
