import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
interface Career { playerName:string; matches:number; battingInnings:number; runs:number; highestScore:number; dismissals:number; fours:number; sixes:number; battingBalls:number; battingAverage:number; strikeRate:number; bowlingBalls:number; runsConceded:number; wickets:number; bestWickets:number; economy:number; }
@Component({selector:'app-player-form',standalone:true,imports:[CommonModule,RouterLink],template:`
<section class="page">
@if(loading){<section class="card state">Loading player form…</section>}
@else if(career){
<a class="back" [routerLink]="['/players',playerId]">← Player Profile</a>
<header class="hero card"><div><span class="eyebrow">CRICPULSE · PLAYER INTELLIGENCE</span><h1>{{career.playerName}}</h1><p>Career-based performance indicators.</p></div><div class="form-badge" [class.down]="formScore<50">{{formLabel}}</div></header>
<section class="summary-grid"><article class="card stat"><span>PERFORMANCE SCORE</span><strong>{{formScore}}</strong><small>Based on available career output</small></article><article class="card stat"><span>RUNS / INNINGS</span><strong>{{averageRuns}}</strong><small>{{career.runs}} total runs</small></article><article class="card stat"><span>WICKETS / MATCH</span><strong>{{averageWickets}}</strong><small>{{career.wickets}} total wickets</small></article><article class="card stat"><span>BEST SCORE</span><strong>{{career.highestScore}}</strong><small>Career highest</small></article></section>
<section class="grid"><section class="card panel"><div class="head"><div><span class="eyebrow">BATTING PROFILE</span><h2>Career output</h2></div></div><div class="bars"><div class="bar-item"><div class="bar-value">{{career.runs}}</div><div class="bar" [style.height.px]="runBar"></div><span>RUNS</span></div><div class="bar-item"><div class="bar-value">{{career.fours}}</div><div class="bar" [style.height.px]="fourBar"></div><span>4s</span></div><div class="bar-item"><div class="bar-value">{{career.sixes}}</div><div class="bar" [style.height.px]="sixBar"></div><span>6s</span></div><div class="bar-item"><div class="bar-value">{{format(career.strikeRate)}}</div><div class="bar" [style.height.px]="strikeBar"></div><span>SR</span></div></div></section>
<section class="card panel"><div class="head"><div><span class="eyebrow">BOWLING PROFILE</span><h2>Career output</h2></div></div><div class="bars"><div class="bar-item"><div class="bar-value">{{career.wickets}}</div><div class="bar wicket-bar" [style.height.px]="wicketBar"></div><span>WICKETS</span></div><div class="bar-item"><div class="bar-value">{{career.bestWickets}}</div><div class="bar wicket-bar" [style.height.px]="bestWicketBar"></div><span>BEST</span></div><div class="bar-item"><div class="bar-value">{{format(career.economy)}}</div><div class="bar wicket-bar" [style.height.px]="economyBar"></div><span>ECON</span></div></div></section></section>
<section class="card panel table-card"><div class="head"><div><span class="eyebrow">CAREER FORM</span><h2>Performance summary</h2></div></div><div class="table-wrap"><table><thead><tr><th>METRIC</th><th>VALUE</th><th>CONTEXT</th></tr></thead><tbody><tr><td>Matches</td><td>{{career.matches}}</td><td>Career matches</td></tr><tr><td>Batting Average</td><td>{{format(career.battingAverage)}}</td><td>{{career.dismissals}} dismissals</td></tr><tr><td>Strike Rate</td><td>{{format(career.strikeRate)}}</td><td>{{career.battingBalls}} balls faced</td></tr><tr><td>Wickets</td><td>{{career.wickets}}</td><td>Best {{career.bestWickets}} in an innings</td></tr><tr><td>Economy</td><td>{{format(career.economy)}}</td><td>{{overs(career.bowlingBalls)}} overs</td></tr></tbody></table></div></section>
<section class="card insight"><span class="eyebrow">FORM INSIGHT</span><h2>{{insight}}</h2><p>This is an analytical indicator, not an official cricket statistic. It does not change match results or career totals.</p></section>
} @else {<section class="card state"><h2>Player form unavailable</h2><a routerLink="/players/statistics">Back to rankings →</a></section>}
</section>`,styles:[`:host{display:block}.page{max-width:1180px;margin:auto;padding:34px 4vw 100px;color:#edf8f2}.card{border:1px solid #ffffff16;border-radius:22px;background:linear-gradient(180deg,#0f271ee8,#091712f7);box-shadow:0 18px 50px #0006}.back{display:inline-block;margin-bottom:18px;color:#91aa9d;text-decoration:none;font-size:12px}.back:hover{color:#b8f45c}.eyebrow{display:block;color:#789386;font-size:9px;font-weight:900;letter-spacing:2px}.hero{display:flex;justify-content:space-between;align-items:center;padding:30px}.hero h1{margin:8px 0 5px;font-size:clamp(36px,5vw,58px);letter-spacing:-3px}.hero p{margin:0;color:#91aa9d;font-size:11px}.form-badge{padding:13px 16px;border-radius:13px;background:#b8f45c;color:#10251e;font-size:12px;font-weight:950;letter-spacing:1px}.form-badge.down{background:#ff766d;color:#21100f}.summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.stat{padding:20px}.stat span{display:block;color:#789386;font-size:8px;font-weight:900;letter-spacing:1.5px}.stat strong{display:block;margin:10px 0 4px;font-size:37px;line-height:1;letter-spacing:-2px}.stat small{color:#789386;font-size:9px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{padding:22px}.head{display:flex;justify-content:space-between;margin-bottom:18px}.head h2{margin:6px 0 0;font-size:18px}.bars{height:220px;display:flex;align-items:end;justify-content:space-around;gap:10px;padding:20px 5px 0;border-bottom:1px solid #ffffff14}.bar-item{height:100%;flex:1;display:flex;flex-direction:column;justify-content:end;align-items:center;min-width:25px}.bar-value{font-size:9px;color:#b8f45c;font-weight:900;margin-bottom:5px}.bar{width:min(34px,70%);height:20px;border-radius:8px 8px 2px 2px;background:#b8f45c}.wicket-bar{background:#edf8f2}.bar-item span{font-size:8px;color:#789386;margin-top:8px}.table-card{margin-top:18px;overflow:hidden}.table-wrap{overflow:auto}table{width:100%;min-width:560px;border-collapse:collapse;table-layout:fixed}th,td{padding:13px 16px;border-top:1px solid #ffffff0d;text-align:right;font-size:10px}th{color:#789386;font-size:8px;letter-spacing:1.4px}th:first-child,td:first-child{text-align:left;width:34%}th:nth-child(2),td:nth-child(2){width:22%}.insight{margin-top:18px;padding:22px}.insight h2{margin:7px 0 5px;font-size:18px}.insight p{margin:0;color:#789386;font-size:10px;line-height:1.6}.state{padding:50px}.state h2{margin-bottom:20px}.state a{padding:12px 16px;background:#b8f45c;color:#10251e;border-radius:10px;text-decoration:none;font-size:10px;font-weight:900}@media(max-width:800px){.summary-grid{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.hero{align-items:flex-start;gap:18px}}@media(max-width:500px){.page{padding:24px 16px 70px}.hero{flex-direction:column}.summary-grid{grid-template-columns:1fr}.bars{height:190px}.form-badge{width:max-content}}`]})
export class PlayerFormComponent{private readonly http=inject(HttpClient);private readonly route=inject(ActivatedRoute);readonly api='http://localhost:8080/api';playerId=this.route.snapshot.paramMap.get('id')||'';loading=true;career:Career|null=null;constructor(){if(this.playerId)this.load();else this.loading=false;}private load(){this.http.get<Career>(`${this.api}/players/${this.playerId}/statistics`).subscribe({next:s=>{this.career=s||null;this.loading=false;},error:()=>{this.career=null;this.loading=false;}});}get averageRuns(){return this.career?.battingInnings? (this.career.runs/this.career.battingInnings).toFixed(1):'0.0';}get averageWickets(){return this.career?.matches?(this.career.wickets/this.career.matches).toFixed(1):'0.0';}get formScore(){if(!this.career)return 0;const runComponent=Math.min(75,(this.career.runs/Math.max(1,this.career.matches))/2);const wicketComponent=Math.min(25,(this.career.wickets/Math.max(1,this.career.matches))*10);return Math.round(runComponent+wicketComponent);}get formLabel(){return this.formScore>=75?'EXCELLENT':this.formScore>=55?'GOOD':this.formScore>=35?'AVERAGE':'NEEDS IMPROVEMENT';}get insight(){if(!this.career)return 'Not enough data to assess form.';if(this.formScore>=75)return 'Strong overall career output with consistent run and/or wicket contribution.';if(this.formScore>=55)return 'Good overall contribution. More completed matches will make the indicator stronger.';if(this.formScore>=35)return 'Mixed output so far. Continue tracking future performances for a reliable trend.';return 'Limited current output. Future matches will provide a more meaningful performance signal.';}get runBar(){return Math.max(12,Math.min(145,20+this.career!.runs/5));}get fourBar(){return Math.max(12,Math.min(145,20+this.career!.fours*8));}get sixBar(){return Math.max(12,Math.min(145,20+this.career!.sixes*10));}get strikeBar(){return Math.max(12,Math.min(145,this.career!.strikeRate*.65));}get wicketBar(){return Math.max(12,Math.min(145,20+this.career!.wickets*12));}get bestWicketBar(){return Math.max(12,Math.min(145,20+this.career!.bestWickets*20));}get economyBar(){return Math.max(12,Math.min(145,150-Math.min(138,this.career!.economy*12)));}format(v:number){return Number(v||0).toFixed(2);}overs(balls:number){return `${Math.floor((balls||0)/6)}.${(balls||0)%6}`;}}
