import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';

interface PlayerStatistics { playerId:string; playerName:string; matches:number; battingInnings:number; runs:number; highestScore:number; dismissals:number; fours:number; sixes:number; battingBalls:number; battingAverage:number; strikeRate:number; bowlingBalls:number; runsConceded:number; wickets:number; bestWickets:number; economy:number; }
@Component({selector:'app-player-statistics',standalone:true,imports:[CommonModule,RouterLink],template:`
<section class="page"><header class="hero"><div><span class="eyebrow">CRICPULSE · PLAYER CENTRE</span><h1>Career Statistics</h1><p>Historical performance aggregated from completed ball-by-ball match data.</p></div><a class="back" routerLink="/players">Players</a></header>
@if(loading){<section class="card state">Loading player statistics…</section>}@else if(players.length){
<section class="stats"><article class="card"><span>PLAYERS</span><strong>{{players.length}}</strong><small>With recorded match performance</small></article><article class="card"><span>TOTAL RUNS</span><strong>{{totalRuns}}</strong><small>Across recorded innings</small></article><article class="card"><span>TOTAL WICKETS</span><strong>{{totalWickets}}</strong><small>Across recorded bowling innings</small></article><article class="card"><span>TOTAL SIXES</span><strong>{{totalSixes}}</strong><small>Recorded boundaries</small></article></section>
<section class="card table-card"><div class="title"><span class="eyebrow">PLAYER RANKINGS</span><h2>Batting & Bowling</h2></div><div class="table-wrap"><table><thead><tr><th>PLAYER</th><th>M</th><th>RUNS</th><th>AVG</th><th>SR</th><th>4s</th><th>6s</th><th>W</th><th>ECON</th><th>BEST</th></tr></thead><tbody>@for(p of players;track p.playerId){<tr><td><a class="player-link" [routerLink]="['/players',p.playerId]"><strong>{{p.playerName}}</strong><span>View profile →</span></a></td><td>{{p.matches}}</td><td class="accent">{{p.runs}}</td><td>{{format(p.battingAverage)}}</td><td>{{format(p.strikeRate)}}</td><td>{{p.fours}}</td><td>{{p.sixes}}</td><td class="accent">{{p.wickets}}</td><td>{{format(p.economy)}}</td><td>{{p.bestWickets}}</td></tr>}</tbody></table></div></section>
<section class="card note"><span class="eyebrow">STATISTICS ENGINE</span><h2>Built from match events</h2><p>These figures are aggregated from stored innings batting and bowling records. Live scoring, innings transitions and existing match-result calculations are not modified by this screen.</p></section>
}@else{<section class="card state"><h2>No player statistics yet</h2><p>Complete a match with recorded batting or bowling data to populate career statistics.</p></section>}</section>`,styles:[`:host{display:block}.page{max-width:1220px;margin:auto;padding:36px 4vw 100px;color:#edf8f2}.hero{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.eyebrow{display:block;color:#789386;font-size:9px;font-weight:900;letter-spacing:2px}.hero h1{margin:8px 0 6px;font-size:clamp(38px,5vw,62px);letter-spacing:-3px;line-height:.92}.hero p{margin:0;color:#91aa9d;font-size:11px}.back{padding:10px 14px;border:1px solid #ffffff18;border-radius:11px;color:#edf8f2;text-decoration:none;font-size:10px;font-weight:900}.card{border:1px solid #ffffff16;border-radius:20px;background:linear-gradient(180deg,#0f271ee8,#091712f7);box-shadow:0 18px 50px #0006}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.stats article{padding:20px}.stats span{display:block;color:#789386;font-size:8px;font-weight:900;letter-spacing:1.5px}.stats strong{display:block;margin:10px 0 5px;font-size:35px;letter-spacing:-2px}.stats small{color:#789386;font-size:9px}.table-card{overflow:hidden}.title{padding:22px 24px 14px}.title h2{margin:6px 0 0;font-size:19px}.table-wrap{overflow:auto}table{width:100%;min-width:900px;border-collapse:collapse;table-layout:fixed}th,td{padding:13px 14px;border-top:1px solid #ffffff0d;text-align:right;font-size:10px;font-variant-numeric:tabular-nums}th{color:#789386;font-size:8px;letter-spacing:1.2px;font-weight:900;background:#ffffff04}th:first-child,td:first-child{text-align:left;width:24%}th:not(:first-child),td:not(:first-child){width:8.44%}td strong{font-size:11px}.player-link{display:flex;flex-direction:column;gap:3px;color:#edf8f2;text-decoration:none}.player-link:hover strong{color:#c9ff71}.player-link span{color:#789386;font-size:8px}.accent{color:#c9ff71;font-weight:900}.note{margin-top:18px;padding:22px}.note h2{margin:7px 0}.note p{margin:0;color:#91aa9d;font-size:10px;line-height:1.7}.state{padding:50px}.state h2{margin:0 0 8px}.state p{color:#91aa9d}@media(max-width:850px){.stats{grid-template-columns:1fr 1fr}}@media(max-width:550px){.page{padding:24px 16px 70px}.hero{align-items:flex-start;flex-direction:column;gap:15px}.stats{grid-template-columns:1fr}.back{width:max-content}}`]})
export class PlayerStatisticsComponent { private readonly http=inject(HttpClient); readonly api='http://localhost:8080/api'; players:PlayerStatistics[]=[]; loading=true; constructor(){this.http.get<PlayerStatistics[]>(`${this.api}/players/statistics`).subscribe({next:r=>{this.players=r||[];this.loading=false;},error:()=>{this.players=[];this.loading=false;}});} get totalRuns(){return this.players.reduce((s,p)=>s+p.runs,0);} get totalWickets(){return this.players.reduce((s,p)=>s+p.wickets,0);} get totalSixes(){return this.players.reduce((s,p)=>s+p.sixes,0);} format(v:number){return (v||0).toFixed(2);} }
