import { Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';

interface Team { id:string; name:string; city?:string; ownerId:string; }
interface Member { teamId:string; playerId:string; userId:string; fullName:string; email:string; phone?:string; role:string; }
interface TeamAccess { teamId:string; role:string; canManage:boolean; }

@Component({selector:'app-team-detail',standalone:true,imports:[RouterLink],template:`
<section class="page">
@if(team){
<header class="hero"><div><div class="eyebrow">TEAM MANAGEMENT</div><h1>{{team.name}}</h1><p>◉ {{team.city || 'Location not set'}} · {{access?.role || 'MEMBER'}}</p></div><button class="back" (click)="history.back()">← Back</button></header>
<div class="stats"><div><b>{{members.length}}</b><span>Squad Members</span></div><div><b>{{count('CAPTAIN')}}</b><span>Captain</span></div><div><b>{{count('MANAGER')}}</b><span>Manager</span></div><div><b>{{count('PLAYER')}}</b><span>Players</span></div></div>
<section class="card"><div class="section-head"><div><div class="eyebrow">SQUAD</div><h2>Team Members</h2></div>@if(access?.canManage){<div class="actions"><a class="secondary" [routerLink]="['/dashboard/teams',team.id,'players','bulk']">+ Create Multiple Players</a><button class="primary" (click)="showAdd=true">+ Add Existing</button></div>}</div>
@if(showAdd && access?.canManage){<div class="add"><input [value]="email" placeholder="Registered player email" (input)="email=$any($event.target).value"><select [value]="role" (change)="role=$any($event.target).value"><option>PLAYER</option><option>CAPTAIN</option><option>VICE_CAPTAIN</option><option>MANAGER</option></select><button class="primary" (click)="addMember()">Add</button><button class="ghost" (click)="showAdd=false">Cancel</button></div>}
<div class="members">@for(m of members;track m.playerId){<article class="member"><div class="avatar">{{m.fullName.charAt(0).toUpperCase()}}</div><div class="identity"><strong>{{m.fullName}}</strong><small>{{m.email}} · {{m.role}}</small></div>@if(access?.canManage){<select [value]="m.role" [disabled]="m.role==='OWNER'" (change)="changeRole(m,$any($event.target).value)"><option>OWNER</option><option>MANAGER</option><option>CAPTAIN</option><option>VICE_CAPTAIN</option><option>PLAYER</option></select><button class="remove" [disabled]="m.role==='OWNER'" (click)="remove(m)">Remove</button>}</article>} @empty {<div class="empty">No squad members yet.</div>}</div>
</section>
@if(toast){<div class="toast" [class.error]="toastType==='error'">{{toast}}</div>}
}@else{<div class="empty full">Loading team...</div>}
</section>`,styles:[`:host{display:block}.page{max-width:1150px;padding:42px 4vw 100px}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:26px}.eyebrow{color:#b8f45c;font-size:10px;font-weight:850;letter-spacing:2px}h1{font-size:clamp(34px,5vw,52px);letter-spacing:-3px;margin:8px 0}h2{margin:7px 0;font-size:27px}p,small{color:#91aa9d}.back,.ghost,.remove{border:1px solid #ffffff18;background:#0c2119;color:#dbe9e1;border-radius:9px;padding:11px 14px;cursor:pointer}.primary,.secondary{border:0;border-radius:9px;padding:11px 15px;font-weight:850;cursor:pointer;text-decoration:none}.primary{background:#b8f45c;color:#10251e}.secondary{background:#173d2d;color:#b8f45c;border:1px solid #b8f45c33}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.stats div,.card{background:#0c2119d9;border:1px solid #ffffff15;border-radius:18px;padding:20px}.stats b{display:block;font-size:28px}.stats span{font-size:11px;color:#789386}.section-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:18px}.actions{display:flex;gap:8px}.add{display:flex;gap:9px;padding:14px;border:1px solid #b8f45c30;border-radius:13px;margin-bottom:15px}.add input,.add select,.member select{background:#081a14;color:#dbe9e1;border:1px solid #ffffff18;border-radius:8px;padding:10px}.add input{flex:1}.members{display:grid;gap:9px}.member{display:flex;align-items:center;gap:13px;padding:13px;border:1px solid #ffffff0d;border-radius:12px;background:#091a14}.avatar{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;background:#173d2d;color:#b8f45c;font-weight:900}.identity{flex:1;display:grid;gap:3px}.identity strong{font-size:14px}.member select{font-size:11px}.remove{font-size:11px}.remove:disabled,.member select:disabled{opacity:.45;cursor:not-allowed}.empty{text-align:center;padding:35px;color:#789386}.full{margin-top:50px}.toast{position:fixed;right:24px;bottom:24px;z-index:1000;background:#173d2d;color:#dbe9e1;border:1px solid #b8f45c55;border-radius:12px;padding:13px 16px;box-shadow:0 12px 40px #0008}.toast.error{border-color:#ff6b6b66}@media(max-width:700px){.hero,.section-head,.add{flex-direction:column;align-items:stretch}.actions{flex-direction:column}.stats{grid-template-columns:repeat(2,1fr)}.member{flex-wrap:wrap}.identity{min-width:150px}.member select{flex:1}}`]
})
export class TeamDetailComponent {
  private http=inject(HttpClient); private route=inject(ActivatedRoute); history=window.history;
  team:Team|null=null; members:Member[]=[]; access:TeamAccess|null=null; email=''; role='PLAYER'; showAdd=false; toast=''; toastType:'success'|'error'='success';
  constructor(){const id=this.route.snapshot.paramMap.get('id');if(id)this.http.get<Team>(`http://localhost:8080/api/teams/${id}`).subscribe({next:t=>{this.team=t;this.loadAccess(id);this.loadMembers(id)},error:e=>this.showToast(e?.error?.message||'Unable to load team','error')});}
  loadAccess(id:string){this.http.get<TeamAccess>(`http://localhost:8080/api/teams/${id}/access`).subscribe({next:x=>this.access=x,error:e=>this.showToast(e?.error?.message||'Unable to load team access','error')})}
  loadMembers(id:string){this.http.get<Member[]>(`http://localhost:8080/api/teams/${id}/members`).subscribe({next:x=>this.members=x,error:e=>this.showToast(e?.error?.message||'Unable to load squad','error')})}
  count(role:string){return this.members.filter(x=>x.role===role).length}
  addMember(){if(!this.team||!this.email.trim()||!this.access?.canManage)return;this.http.post<Member>(`http://localhost:8080/api/teams/${this.team.id}/members`,{email:this.email.trim(),role:this.role}).subscribe({next:m=>{this.members=[...this.members.filter(x=>x.playerId!==m.playerId),m];this.email='';this.showAdd=false;this.showToast(`${m.fullName} added to ${this.team!.name}`,'success')},error:e=>this.showToast(e?.error?.message||'Unable to add player','error')})}
  changeRole(m:Member,role:string){if(!this.team||!this.access?.canManage||m.role==='OWNER')return;this.http.patch<Member>(`http://localhost:8080/api/teams/${this.team.id}/members/${m.playerId}`,{role}).subscribe({next:x=>{m.role=x.role;this.showToast(`${m.fullName} is now ${x.role}`,'success')},error:e=>this.showToast(e?.error?.message||'Unable to change role','error')})}
  remove(m:Member){if(!this.team||!this.access?.canManage||m.role==='OWNER'||!confirm(`Remove ${m.fullName} from this team?`))return;this.http.delete(`http://localhost:8080/api/teams/${this.team.id}/members/${m.playerId}`).subscribe({next:()=>{this.members=this.members.filter(x=>x.playerId!==m.playerId);this.showToast(`${m.fullName} removed from the team`,'success')},error:e=>this.showToast(e?.error?.message||'Unable to remove player','error')})}
  showToast(message:string,type:'success'|'error'){this.toast=message;this.toastType=type;window.setTimeout(()=>this.toast='',3500)}
}
