import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';

interface Team { id: string; name: string; city?: string; ownerId: string; }
interface Player { id: string; userId: string; name: string; battingStyle?: string; bowlingStyle?: string; role: string; }

@Component({
  selector: 'app-teams', standalone: true, imports: [RouterLink],
  template: `<section class="teams-page">@if(team){<section class="team-hero"><div class="team-identity"><div class="team-logo">{{team.name.charAt(0).toUpperCase()}}</div><div><div class="eyebrow">ACTIVE TEAM</div><h1>{{team.name}}</h1><p>◉ {{team.city || 'Location not set'}} · Created by you</p></div></div><button class="edit">Edit team <span>✎</span></button></section><div class="stats"><div><small>ROSTER</small><b>{{players.length}}</b><span>players</span></div><div><small>MATCHES</small><b>0</b><span>played</span></div><div><small>WIN RATE</small><b>—</b><span>this season</span></div><div><small>STATUS</small><b class="ready">●</b><span>active</span></div></div><section class="section-heading"><div><div class="eyebrow">SQUAD MANAGEMENT</div><h2>Team roster</h2></div><button class="primary" routerLink="/player/onboarding">+ Add player</button></section>@if(players.length){<div class="roster">@for(player of players; track player.id){<article class="player-card"><div class="avatar">{{initials(player.name)}}</div><div class="player-main"><b>{{player.name}}</b><small>{{player.role || 'PLAYER'}}</small></div><div class="styles"><span>{{format(player.battingStyle)}}</span><span>{{format(player.bowlingStyle)}}</span></div><button class="more">•••</button></article>}</div>}@else{<section class="empty"><div class="empty-icon">♙</div><h3>Your roster is waiting</h3><p>Add players to build your squad and prepare for your first match.</p><button class="primary" routerLink="/player/onboarding">Set up player profile →</button></section>}}@else{<section class="empty"><div class="empty-icon">◈</div><h3>Create your team first</h3><p>Your team profile will appear here once you create your first team.</p><button class="primary" routerLink="/teams/new">Create team →</button></section>}</section>`,
  styles: [`:host{display:block}.teams-page{max-width:1100px;padding:55px 4vw 100px}.team-hero{display:flex;justify-content:space-between;align-items:center;padding:28px;border:1px solid #b8f45c35;border-radius:22px;background:linear-gradient(110deg,#173d2dbb,#0c2119d9)}.team-identity{display:flex;align-items:center;gap:18px}.team-logo{display:grid;place-items:center;width:76px;height:76px;border-radius:20px;background:#b8f45c;color:#10251e;font-size:34px;font-weight:900;box-shadow:0 12px 30px #b8f45c25}.eyebrow{color:#b8f45c;font-size:10px;font-weight:850;letter-spacing:2px}h1{margin:8px 0;font-size:clamp(30px,5vw,52px);letter-spacing:-3px}p{color:#91aa9d;margin:0}.edit,.more{border:1px solid #ffffff1c;border-radius:9px;background:#ffffff08;color:#b9ccc2;padding:11px 14px;cursor:pointer}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0 55px}.stats>div{display:grid;gap:6px;padding:18px;border:1px solid #ffffff15;border-radius:14px;background:#0c2119d9}.stats small{color:#789386;font-size:9px;letter-spacing:1.3px}.stats b{font-size:25px}.stats span{color:#789386;font-size:11px}.stats .ready{color:#b8f45c}.section-heading{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}h2{margin:9px 0 0;font-size:27px;letter-spacing:-1px}.primary{padding:12px 16px;border:0;border-radius:9px;background:#b8f45c;color:#10251e;font-weight:850;cursor:pointer}.roster{display:grid;gap:10px}.player-card{display:flex;align-items:center;gap:14px;padding:15px 18px;border:1px solid #ffffff15;border-radius:14px;background:#0c2119d9}.avatar{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#315944;color:#b8f45c;font-size:12px;font-weight:850}.player-main{display:grid;gap:5px;min-width:170px}.player-main small{color:#789386;font-size:9px;letter-spacing:1px}.styles{display:flex;gap:8px;flex:1}.styles span{padding:6px 8px;border-radius:6px;background:#ffffff08;color:#91aa9d;font-size:10px}.more{font-size:14px;border:0}.empty{padding:70px 20px;border:1px solid #ffffff15;border-radius:18px;background:#0c2119d9;text-align:center}.empty-icon{color:#b8f45c;font-size:35px}.empty h3{font-size:21px;margin:15px 0 8px}.empty p{margin-bottom:22px}@media(max-width:700px){.teams-page{padding:40px 20px 90px}.team-hero{align-items:flex-start;gap:20px;flex-direction:column}.stats{grid-template-columns:repeat(2,1fr);margin-bottom:40px}.section-heading{align-items:flex-start;gap:15px;flex-direction:column}.player-card{flex-wrap:wrap}.styles{width:100%;padding-left:56px}.more{margin-left:auto}}
  `]
})
export class TeamsComponent {
  private readonly http = inject(HttpClient);
  team: Team | null = null; players: Player[] = [];
  constructor() { const saved = localStorage.getItem('cricketpulse_team'); if (saved) { this.team = JSON.parse(saved) as Team; this.loadPlayers(); } }
  loadPlayers(): void { if (!this.team) return; this.http.get<Player[]>(`http://localhost:8080/api/players/teams/${this.team.id}`).subscribe({ next: players => this.players = players }); }
  initials(name: string): string { return name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(); }
  format(value?: string): string { return (value || 'Not set').replaceAll('_', ' ').toLowerCase().replace(/^\w/, value => value.toUpperCase()); }
}
