import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

interface Point { teamId:string; teamName:string; played:number; wins:number; losses:number; ties:number; points:number; runsFor:number; runsAgainst:number; nrr:number; }
interface Qualifier { seed:number; label:string; higherSeed:Point; lowerSeed:Point; }
interface Preview { eligible:boolean; message:string; table:Point[]; qualifiers:Qualifier[]; }

@Component({
 selector:'app-tournament-qualification', standalone:true, imports:[CommonModule,RouterLink],
 template:`<section class="page"><a class="back" [routerLink]="['/tournaments',id]">← Tournament</a>@if(loading){<section class="card state">Loading qualification preview…</section>}@else if(preview){<header class="hero card"><div><span class="eyebrow">CRICPULSE · PLAYOFF ENGINE</span><h1>Qualification</h1><p>Current projection from the live points table.</p></div><span class="badge">{{preview.eligible?'TOP 4':'NOT READY'}}</span></header><div class="notice" [class.warn]="!preview.eligible">{{preview.message}}</div>@if(preview.eligible){<section class="bracket"><article class="card playoff"><span class="eyebrow">QUALIFIER 1</span><h2>#1 {{preview.qualifiers[0].higherSeed.teamName}}</h2><div class="vs">vs</div><h2>#4 {{preview.qualifiers[0].lowerSeed.teamName}}</h2><small>Current seeds · no matches created</small></article><article class="card playoff"><span class="eyebrow">QUALIFIER 2</span><h2>#2 {{preview.qualifiers[1].higherSeed.teamName}}</h2><div class="vs">vs</div><h2>#3 {{preview.qualifiers[1].lowerSeed.teamName}}</h2><small>Current seeds · no matches created</small></article></section>}<section class="card panel"><div class="head"><div><span class="eyebrow">LIVE STANDINGS</span><h2>Qualification order</h2></div></div>@if(preview.table.length){<div class="table-wrap"><table><thead><tr><th>#</th><th>TEAM</th><th>P</th><th>W</th><th>L</th><th>PTS</th><th>NRR</th></tr></thead><tbody>@for(p of preview.table;track p.teamId;let i=$index){<tr [class.qualified]="preview.eligible&&i<4"><td>{{i+1}}</td><td><strong>{{p.teamName}}</strong></td><td>{{p.played}}</td><td>{{p.wins}}</td><td>{{p.losses}}</td><td>{{p.points}}</td><td>{{p.nrr|number:'1.3-3'}}</td></tr>}</tbody></table></div>}@else{<p class="muted">No standings yet. Complete tournament matches to build qualification order.</p>}</section><div class="actions"><a [routerLink]="['/tournaments',id]">Tournament Control →</a><a [routerLink]="['/tournaments',id,'schedule']">Schedule Fixtures →</a></div>}@else{<section class="card state"><h2>Qualification unavailable</h2><p>{{error||'Unable to load qualification data.'}}</p><a [routerLink]="['/tournaments',id]">Back to tournament →</a></section>}</section>`,
 styles:[`:host{display:block}.page{max-width:1100px;margin:auto;padding:34px 4vw 100px;color:#edf8f2}.card{border:1px solid #ffffff16;border-radius:22px;background:linear-gradient(180deg,#0f271ee8,#091712f7);box-shadow:0 18px 50px #0006}.back{display:inline-block;margin-bottom:18px;color:#91aa9d;text-decoration:none;font-size:12px}.back:hover{color:#b8f45c}.eyebrow{display:block;color:#789386;font-size:9px;font-weight:900;letter-spacing:2px}.hero{display:flex;justify-content:space-between;align-items:center;padding:30px}.hero h1{margin:8px 0 5px;font-size:clamp(38px,6vw,62px);letter-spacing:-3px}.hero p{margin:0;color:#91aa9d;font-size:11px}.badge{padding:9px 12px;border-radius:99px;background:#b8f45c15;color:#b8f45c;font-size:8px;font-weight:900;letter-spacing:1px}.notice{margin:18px 0;padding:14px 16px;border:1px solid #b8f45c20;border-radius:13px;background:#b8f45c0b;color:#b8f45c;font-size:10px}.notice.warn{border-color:#ffb35c33;background:#ffb35c0b;color:#ffbe73}.bracket{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:18px 0}.playoff{padding:24px;text-align:center}.playoff h2{margin:12px 0;font-size:20px}.playoff .vs{color:#b8f45c;font-size:9px;font-weight:950;letter-spacing:2px}.playoff small{display:block;margin-top:14px;color:#789386;font-size:8px}.panel{padding:22px;margin-top:18px}.head{display:flex;justify-content:space-between}.head h2{margin:6px 0 0;font-size:19px}.table-wrap{overflow:auto}table{width:100%;min-width:620px;border-collapse:collapse;table-layout:fixed}th,td{padding:13px 15px;border-top:1px solid #ffffff0d;text-align:right;font-size:10px}th{color:#789386;font-size:8px;letter-spacing:1.2px}th:first-child,td:first-child{width:8%;text-align:left}th:nth-child(2),td:nth-child(2){width:38%;text-align:left}.qualified{background:#b8f45c06}.qualified td:first-child,.qualified td:nth-child(2){color:#b8f45c}.muted{color:#789386;font-size:10px}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.actions a,.state a{padding:12px 16px;border-radius:11px;background:#b8f45c;color:#10251e;text-decoration:none;font-size:10px;font-weight:900}.state{padding:50px}.state h2{margin-bottom:8px}.state p{color:#789386;font-size:10px}@media(max-width:700px){.hero{align-items:flex-start;gap:15px}.bracket{grid-template-columns:1fr}.actions{flex-direction:column}.actions a{text-align:center}}@media(max-width:480px){.page{padding:24px 16px 70px}.hero{flex-direction:column}.hero h1{font-size:42px}}`]
})
export class TournamentQualificationComponent {
 private readonly http=inject(HttpClient); private readonly route=inject(ActivatedRoute); readonly api='http://localhost:8080/api';
 id=this.route.snapshot.paramMap.get('id')||''; loading=true; preview:Preview|null=null; error='';
 constructor(){if(this.id)this.load();else this.loading=false;}
 load(){this.http.get<Preview>(`${this.api}/tournaments/${this.id}/qualification`).subscribe({next:r=>{this.preview=r;this.loading=false;},error:e=>{this.error=e?.error?.message||'Unable to load qualification preview.';this.loading=false;}});}
}
